# Generated by Django 5.1.1 on 2024-09-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55)),
                ('exp', models.IntegerField()),
                ('skills', models.CharField(max_length=66)),
            ],
        ),
    ]
